[versions]
kotlin = "2.1.0"
junit = "5.11.4"
assertk = "0.28.1"

[libraries]
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
assertk = { module = "com.willowtreeapps.assertk:assertk", version.ref = "assertk" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
